server:
  port: 8081
spring:
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: top.hellooooo.job.pojo
