spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.17.130:3306/job?serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      # 设置上传文件大小为1G
      max-file-size: 1000MB
      # 单个请求文件最大25M
      max-request-size: 25MB
logging:
  level:
    root: info

file:
  basepath: D:\BaiduNetdiskDownload\